[tool.commitizen]
name = "cz_conventional_commits"
version = "0.9.2"
tag_format = "v$version"
version_files = [
    ".cz.toml:version"
]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
changelog_incremental = true
changelog_start_rev = "v0.9.2"
